// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package infra

import (
	"database/sql"
)

type Account struct {
	ID        int32         `json:"id"`
	TenantID  sql.NullInt32 `json:"tenant_id"`
	Status    string        `json:"status"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}

type Card struct {
	ID        int32          `json:"id"`
	AccountID sql.NullInt32  `json:"account_id"`
	Amount    sql.NullString `json:"amount"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

type Tenant struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
