// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenant.sql

package infra

import (
	"context"
)

const getTenant = `-- name: GetTenant :one
SELECT id, name FROM
tenants WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id int32) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
