// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transaction.sql

package infra

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    card_id,
    kind,
    value
) VALUES (
    $1, $2, $3
) RETURNING id, card_id, kind, value, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	CardID int32  `json:"card_id"`
	Kind   string `json:"kind"`
	Value  int64  `json:"value"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, arg.CardID, arg.Kind, arg.Value)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Kind,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, card_id, kind, value, created_at, updated_at, deleted_at FROM transactions 
WHERE card_id = $1 AND id = $2
LIMIT 1
`

type GetTransactionParams struct {
	CardID int32 `json:"card_id"`
	ID     int32 `json:"id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, arg.CardID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Kind,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, card_id, kind, value, created_at, updated_at, deleted_at FROM transactions 
WHERE card_id = $1
`

func (q *Queries) GetTransactions(ctx context.Context, cardID int32) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Kind,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactions = `-- name: SearchTransactions :many
SELECT
t.id,
t.card_id,
t.kind,
t.value
FROM transactions t
JOIN cards c ON t.card_id = c.id
JOIN accounts a ON c.account_id = a.id
WHERE a.tenant_id = $1 AND a.id = $2
`

type SearchTransactionsParams struct {
	TenantID  int32 `json:"tenant_id"`
	Accountid int32 `json:"accountid"`
}

type SearchTransactionsRow struct {
	ID     int32  `json:"id"`
	CardID int32  `json:"card_id"`
	Kind   string `json:"kind"`
	Value  int64  `json:"value"`
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]SearchTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTransactions, arg.TenantID, arg.Accountid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTransactionsRow{}
	for rows.Next() {
		var i SearchTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Kind,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
