name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users-transactions-api

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.4"
          cache: false
      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.0
          args: --timeout 3m --config .golangci.yaml

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users-transactions-api

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22.4"
      - name: Run Tests
        run: go test -cover -race ./... -v
