name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users-transactions-api

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: Check out code
        uses: actions/checkout@v4
      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v3

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users-transactions-api

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run Tests
        run: go test -cover -race ./... -v
